### ISSUE TITLE
Added this to Awesome-NLP too!

### ISSUE THREAD

**Issue by NirantK** [kmkurn/id-nlp-resource#3]
Hey, thanks for putting this amazing resource on Indonesian NLP Resources together. 

I'm the maintainer and [awesome-nlp](https://github.com/keon/awesome-nlp/tree/master) and I've added some of these sources under the Indonesian Section with due [credits](https://github.com/keon/awesome-nlp/blob/master/CREDITS.md)! 

Please consider contributing there directly as well, it will allow for a much better reach!

**Comment by kmkurn** [comment]
Thanks for doing that and letting me know!
